name: Report an issue
description: Report an issue
title: "[Issue]: "
labels: ["mobile app"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report! The more information you provide about your case the sooner we can reproduce the issue and improve the app.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
    validations:
      required: true  
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: Operating system
    attributes:
      options:
        - Android
        - iOS
  - type: textarea
    id: comments
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
