name: Report an issue
description: Report an issue
title: "[Issue]: "
labels: ["mobile app"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report! The more information you provide about your case the sooner we can reproduce the issue and improve the app.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
    validations:
      required: true  
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: Operating system
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, drag and drop in this field screenshots to help explain your problem. 
        Android: can be created by pressing the Volume Down and Power Button at the same time.
        iOS: On an iPhone with Face ID - simultaneously press and then release the side button and volume up button. On an iPhone with a Home button - simultaneously press and then release the Home button and the side button or Sleep/Wake button (depending on your model).
  - type: textarea
    id: comments
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
